---
- name: install MySQL packages
  yum: name={{item}} state=installed enablerepo="{{mysql_enablerepo}}"
  with_items: "{{mysql_packages}}"

- name: install MySQL-python
  yum: name=MySQL-python state=installed enablerepo={{mysql_enablerepo}}

- name: service start & enabled
  service: name=mysqld state=started enabled=yes
