---
- name: master_playbook
  # sudo実行の有無
  become: yes
  # 対象クライアント
  hosts:
    - db
  # 参照パラメータ(優先順位はhostvars>group_vars)
  vars_files:
    - group_vars/vars_pretask_ansible.yml
    - group_vars/vars_common.yml
    - group_vars/vars_fw_iptables.yml
    # - group_vars/vars_ha_heartbeat_drbd.yml
    # - group_vars/vars_test_serverspec.yml
    # - group_vars/vars_db_mongodb.yml
    # - group_vars/vars_web_apache.yml
    # - group_vars/vars_web_nginx.yml
    # - group_vars/vars_db_mysql.ym
    # - group_vars/vars_monitoring_mackerel.yml
    # - host_vars/vars_{{ansible_hostname}}.yml
  # 操作手順
  roles:
    - common
    - fw_iptables
    # - test_serverspec
    # - ha_heartbeat_drbd
    # - db_mongodb
    # - web_apache
    # - web_nginx
    # - db_mysql
    # - monitoring_mackerel
