---
- include: set_timezone.yml
- include: set_locale.yml
- include: set_keyboard.yml
- include: set_hostname.yml
- include: set_su.yml
- include: set_user.yml
- include: set_ssh.yml
- include: set_yumrepository.yml
- include: set_common_packages.yml
- include: set_selinux.yml
- include: set_ipv6.yml
- include: set_logrotate.yml
- include: set_logwatch.yml
- include: set_services.yml
- include: set_src_directory.yml
- include: set_gaiconf.yml
- include: set_ntp.yml
- include: set_hosts.yml


# - include: set_kernel_param.yml

# - include: set_network.yml
# // vi /etc/sysconfig/network

# - include: set_ifcfg.yml
# // vi /etc/sysconfig/network-scripts/ifcfg-xx

# - include: set_hosts.yml
# // vi /etc/hosts

# - include: set_resolver.yml
# // vi /etc/resolv.conf
