---
- name: change root password
  user: >
    name=root
    password={{common_user.root.password | password_hash('sha512')}}

- name: create admin-user(wheel group)
  user: >
    name={{item.name}}
    groups="wheel"
    password={{item.password | password_hash('sha512')}}
  with_items:
    - "{{common_user.ansible}}"
    - "{{common_user.wheel}}"

- name: create general-user(non-wheel group)
  user: >
    name={{item.name}}
    password={{item.password | password_hash('sha512')}}
  with_items:
    - "{{common_user.ansible}}"
    - "{{common_user.wheel}}"
