---
- name: set locale
  lineinfile: >
    backup=yes
    dest=/etc/sysconfig/i18n
    state=present
    regexp='{{item.regexp}}'
    line='{{item.line}}'
  with_items:
    - {regexp: '^#? ?LANG', line: 'LANG="{{common_locale.LANG}}"'}
    - {regexp: '^#? ?SUPPORTED', line: 'SUPPORTED="{{common_locale.SUPPORTED}}"'}
    - {regexp: '^#? ?SYSFONT', line: 'SYSFONT="{{common_locale.SYSFONT}}"'}
