---
- name: set sshd
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='{{item.regexp}}'
    line='{{item.line}}'
  with_items:
    - {regexp: '^#? ?Port ', line: 'Port {{common_ssh_port}}'}
    - {regexp: '^#? ?Protocol ', line: 'Protocol 2'}
    - {regexp: '^#? ?PermitRootLogin ', line: 'PermitRootLogin no'}
    - {regexp: '^#? ?PubkeyAuthentication ', line: 'PubkeyAuthentication yes'}
    - {regexp: '^#? ?PermitEmptyPasswords ', line: 'PermitEmptyPasswords no'}
    - {regexp: '^#? ?PasswordAuthentication ', line: 'PasswordAuthentication no'}
    - {regexp: '^#? ?ChallengeResponseAuthentication ', line: 'ChallengeResponseAuthentication no'}
    - {regexp: '^#? ?GSSAPIAuthentication ', line: 'GSSAPIAuthentication no'}
  notify: restart_sshd
