---
- name: cron ntpdate schedule
  cron: >
    name="ntpdate"
    user="root"
    minute=0
    hour=1
    job="/usr/sbin/ntpdate -s -b {{common_ntp_server}}"

- name: startup ntpdate
  lineinfile: >
    dest='/etc/rc.local'
    state=present
    regexp='^#? ?/usr/sbin/ntpdate'
    line='/usr/sbin/ntpdate -s -b {{common_ntp_server}}'
